version: '3.8'

services:
  nextjs-dev:
    container_name: nextjs-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    environment:
      - NODE_ENV=development
    command: npm run dev
  
  flowable-rest:
    image: flowable/flowable-rest
    container_name: flowable-rest
    ports:
      - "8090:8080"
    environment:
      - FLOWABLE_REST_APP_ADMIN_USER=admin
      - FLOWABLE_REST_APP_ADMIN_PASSWORD=
      - FLOWABLE_REST_APP_ADMIN_EMAIL=admin@localhost

  flowable-modeler:
    image: flowable/flowable-modeler
    container_name: flowable-modeler
    ports:
      - "8081:8080"
    environment:
      - FLOWABLE_MODELER_APP_ADMIN_USER=admin
      - FLOWABLE_MODELER_APP_ADMIN_PASSWORD=test